

/*
USER 1 - ADMINISTRATOR
Email: admin@ghanamart.com.gh
Password: Admin123!
Role: administrator

USER 2 - MANAGER  
Email: manager@ghanamart.com.gh
Password: Manager123!
Role: manager

USER 3 - INVENTORY CLERK
Email: inventory@ghanamart.com.gh
Password: Inventory123!
Role: inventory_clerk

USER 4 - CASHIER 1
Email: cashier1@ghanamart.com.gh
Password: Cashier123!
Role: cashier

USER 5 - CASHIER 2
Email: cashier2@ghanamart.com.gh
Password: Cashier123!
Role: cashier

USER 6 - SUPPLIER
Email: supplier@ghanamart.com.gh
Password: Supplier123!
Role: supplier

USER 7 - ASSISTANT MANAGER
Email: assistant.manager@ghanamart.com.gh
Password: Assistant123!
Role: manager

USER 8 - INVENTORY CLERK 2
Email: inventory2@ghanamart.com.gh
Password: Inventory123!
Role: inventory_clerk

USER 9 - NIGHT SHIFT CASHIER
Email: night.cashier@ghanamart.com.gh
Password: NightCash123!
Role: cashier

USER 10 - WAREHOUSE CLERK
Email: warehouse@ghanamart.com.gh
Password: Warehouse123!
Role: inventory_clerk
*/

-- ============================================================================
-- PROFILE DATA TO INSERT AFTER CREATING USERS
-- ============================================================================

-- IMPORTANT: Replace the UUIDs below with the actual user IDs generated by Supabase
-- when you create the users through the dashboard

-- Sample profiles for the users (update UUIDs after user creation)
INSERT INTO profiles (
  id, 
  full_name, 
  email, 
  role, 
  employee_id, 
  contact_phone, 
  department, 
  assigned_areas, 
  shift_info, 
  access_level, 
  is_active
) VALUES 

-- Administrator
('00000000-0000-0000-0000-000000000001', -- Replace with actual UUID from Supabase
 'Kwame Nkrumah', 
 'admin@ghanamart.com.gh', 
 'administrator', 
 'EMP001', 
 '+233-24-111-1111', 
 'Administration', 
 '{"areas": ["all"], "permissions": ["full_access"]}',
 '{"shift": "day", "hours": "8:00-17:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday"]}',
 5, 
 true),

-- Manager
('00000000-0000-0000-0000-000000000002', -- Replace with actual UUID from Supabase
 'Akosua Mensah', 
 'manager@ghanamart.com.gh', 
 'manager', 
 'EMP002', 
 '+233-20-222-2222', 
 'Operations', 
 '{"areas": ["store_floor", "warehouse", "customer_service"], "permissions": ["manage_inventory", "manage_staff", "view_reports"]}',
 '{"shift": "day", "hours": "7:00-16:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]}',
 4, 
 true),

-- Inventory Clerk 1
('00000000-0000-0000-0000-000000000003', -- Replace with actual UUID from Supabase
 'Kofi Asante', 
 'inventory@ghanamart.com.gh', 
 'inventory_clerk', 
 'EMP003', 
 '+233-26-333-3333', 
 'Inventory', 
 '{"areas": ["warehouse", "receiving", "stock_management"], "permissions": ["manage_inventory", "receive_goods", "stock_counts"]}',
 '{"shift": "day", "hours": "6:00-15:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]}',
 3, 
 true),

-- Cashier 1
('00000000-0000-0000-0000-000000000004', -- Replace with actual UUID from Supabase
 'Ama Serwaa', 
 'cashier1@ghanamart.com.gh', 
 'cashier', 
 'EMP004', 
 '+233-54-444-4444', 
 'Sales', 
 '{"areas": ["checkout", "customer_service"], "permissions": ["process_sales", "handle_returns", "customer_management"]}',
 '{"shift": "morning", "hours": "7:00-15:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]}',
 2, 
 true),

-- Cashier 2
('00000000-0000-0000-0000-000000000005', -- Replace with actual UUID from Supabase
 'Yaw Boateng', 
 'cashier2@ghanamart.com.gh', 
 'cashier', 
 'EMP005', 
 '+233-27-555-5555', 
 'Sales', 
 '{"areas": ["checkout", "customer_service"], "permissions": ["process_sales", "handle_returns", "customer_management"]}',
 '{"shift": "evening", "hours": "15:00-23:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"]}',
 2, 
 true),

-- Supplier
('00000000-0000-0000-0000-000000000006', -- Replace with actual UUID from Supabase
 'Abdul Rahman', 
 'supplier@ghanamart.com.gh', 
 'supplier', 
 'SUP001', 
 '+233-30-666-6666', 
 'External', 
 '{"areas": ["supplier_portal"], "permissions": ["view_orders", "update_deliveries", "view_payments"]}',
 '{"shift": "flexible", "hours": "flexible", "days": ["monday", "tuesday", "wednesday", "thursday", "friday"]}',
 1, 
 true),

-- Assistant Manager
('00000000-0000-0000-0000-000000000007', -- Replace with actual UUID from Supabase
 'Efua Adomako', 
 'assistant.manager@ghanamart.com.gh', 
 'manager', 
 'EMP007', 
 '+233-24-777-7777', 
 'Operations', 
 '{"areas": ["store_floor", "customer_service"], "permissions": ["manage_staff", "handle_complaints", "daily_operations"]}',
 '{"shift": "day", "hours": "8:00-17:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]}',
 4, 
 true),

-- Inventory Clerk 2
('00000000-0000-0000-0000-000000000008', -- Replace with actual UUID from Supabase
 'Kwaku Owusu', 
 'inventory2@ghanamart.com.gh', 
 'inventory_clerk', 
 'EMP008', 
 '+233-20-888-8888', 
 'Inventory', 
 '{"areas": ["warehouse", "stock_management"], "permissions": ["manage_inventory", "stock_counts", "reorder_management"]}',
 '{"shift": "evening", "hours": "14:00-22:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday"]}',
 3, 
 true),

-- Night Shift Cashier
('00000000-0000-0000-0000-000000000009', -- Replace with actual UUID from Supabase
 'Adwoa Nyong', 
 'night.cashier@ghanamart.com.gh', 
 'cashier', 
 'EMP009', 
 '+233-26-999-9999', 
 'Sales', 
 '{"areas": ["checkout", "security"], "permissions": ["process_sales", "night_operations", "basic_security"]}',
 '{"shift": "night", "hours": "22:00-06:00", "days": ["friday", "saturday", "sunday"]}',
 2, 
 true),

-- Warehouse Clerk
('00000000-0000-0000-0000-000000000010', -- Replace with actual UUID from Supabase
 'Nana Osei', 
 'warehouse@ghanamart.com.gh', 
 'inventory_clerk', 
 'EMP010', 
 '+233-54-101-0101', 
 'Warehouse', 
 '{"areas": ["warehouse", "receiving", "dispatch"], "permissions": ["warehouse_operations", "goods_receiving", "dispatch_management"]}',
 '{"shift": "day", "hours": "5:00-14:00", "days": ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday"]}',
 3, 
 true);

-- ============================================================================
-- INSTRUCTIONS FOR IMPLEMENTATION
-- ============================================================================

/*
STEP-BY-STEP IMPLEMENTATION:

1. CREATE USERS IN SUPABASE DASHBOARD:
   - Go to your Supabase project dashboard
   - Navigate to Authentication > Users
   - Click "Add User" for each user listed above
   - Use the exact email and password provided
   - Make note of the UUID generated for each user

2. UPDATE THIS SCRIPT:
   - Replace the placeholder UUIDs (00000000-0000-0000-0000-000000000001, etc.)
   - Use the actual UUIDs generated by Supabase for each user

3. RUN THE PROFILE INSERTS:
   - Execute the INSERT INTO profiles statement above
   - This will create the profile records linked to the auth users

4. VERIFY SETUP:
   - Test login with each user account
   - Verify that roles and permissions work correctly
   - Check that user profiles display properly in the application

ALTERNATIVE METHOD (Programmatic):
If you prefer to create users programmatically, you can use the Supabase Admin API
or create a signup script in your application that creates these users automatically.
*/
